import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { db } from "../db.server";

// Loads courses
export const loadCourses = createServerFn({ method: "GET" })
  .inputValidator(z.object({ userId: z.string() }))
  .handler(async ({ data }) => {
    const { userId } = data;

    const courses = db.prepare("SELECT * FROM courses WHERE user_id = ?").all(userId) as any[];

    return courses.map((c) => ({
      id: c.id,
      title: c.title,
      desc: c.desc,
      tag: c.tag,
      progress: c.progress,
      hours: c.hours,
      syllabus: JSON.parse(c.syllabus_json),
    }));
  });

// Resumes/Updates progress of a course
export const updateCourseProgress = createServerFn({ method: "POST" })
  .inputValidator(
    z.object({
      id: z.string(),
      progress: z.number(),
      tag: z.string(),
    })
  )
  .handler(async ({ data }) => {
    const { id, progress, tag } = data;

    db.prepare(`
      UPDATE courses
      SET progress = ?, tag = ?
      WHERE id = ?
    `).run(progress, tag, id);

    return { id, progress, tag };
  });

// Adds a new course generated by AI
export const saveCourse = createServerFn({ method: "POST" })
  .inputValidator(
    z.object({
      userId: z.string(),
      title: z.string(),
      desc: z.string(),
      tag: z.string(),
      progress: z.number(),
      hours: z.string(),
      syllabus: z.array(z.string()),
    })
  )
  .handler(async ({ data }) => {
    const { userId, title, desc, tag, progress, hours, syllabus } = data;
    const id = "course-" + Date.now();
    const syllabus_json = JSON.stringify(syllabus);

    db.prepare(`
      INSERT INTO courses (id, user_id, title, desc, tag, progress, hours, syllabus_json)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `).run(id, userId, title, desc, tag, progress, hours, syllabus_json);

    return {
      id,
      title,
      desc,
      tag,
      progress,
      hours,
      syllabus,
    };
  });
